// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// This file was modified to support strict TypeScript environments
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Sécurité pour garantir à TypeScript que la variable est une string
if (!process.env.DATABASE_URL) {
  throw new Error("🚨 Erreur critique : DATABASE_URL n'est pas définie dans le fichier .env");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env.DATABASE_URL, // Validé et garanti comme non-undefined
  },
});
